# Generated by Django 6.1.1 on 2026-09-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programmes',
            fields=[
                ('programme_id', models.AutoField(primary_key=True, serialize=False)),
                ('programme_name', models.CharField(max_length=100)),
                ('programme_description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('nqf_level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=10)),
                ('credits', models.IntegerField()),
            ],
        ),
    ]
