# Generated by Django 6.1.1 on 2026-09-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facilitators',
            fields=[
                ('facilitator_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('role', models.CharField(choices=[('Facilitator', 'Facilitator'), ('Mentor', 'Mentor')], max_length=50)),
            ],
        ),
    ]
