# Generated by Django 6.1.1 on 2026-09-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Learners',
            fields=[
                ('learner_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('applicaton_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('document_type', models.CharField(choices=[('Affidavit', 'Affidavit'), ('ID', 'ID'), ('CV', 'CV'), ('Matric Certificate', 'Matric Certificate'), ('SARS Document', 'SARS Document')], max_length=50)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
